config/routes.rb
Rails.application.routes.draw do

  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]
  resources :goals
end

app/models/goal.rb
class Goal < ActiveRecord::Base
  belongs_to :user

  validates :title, :user_id, :privacy, :status, presence: true
  validates :privacy, inclusion: %w(Public Private)
  validates :status, inclusion: %w(Incomplete Complete)
end

app/models/goal_comment.rb
class GoalComment < ActiveRecord::Base
  belongs_to :author,
    class_name: "User",
    foreign_key: :user_id

  belongs_to :goal
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_reader :password

  has_many :goals
  has_many :comments

  validates :username, :password_digest, :session_token, presence: true
  validates :username, uniqueness: true
  validates :password, length: { minimum: 6, allow_nil: true }

  after_initialize :ensure_session_token

  def password=(password)
    @password = password

    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def ensure_session_token
    self.session_token ||= SecureRandom::urlsafe_base64
  end

  def reset_session_token!
    self.session_token = SecureRandom::urlsafe_base64
    self.save!
    self.session_token
  end
end

app/models/user_comment.rb
class UserComment < ActiveRecord::Base
  belongs_to :author,
    class_name: "User",
    foreign_key: :user_id

  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  def login!(user)
    session[:session_token] = user.reset_session_token!
  end

  def logout!
    current_user.reset_session_token!
    session[:session_token] = nil
  end

  def current_user
    @current_user ||=
      User.find_by(session_token: session[:session_token])
  end

  def require_current_user!
    if current_user.nil?
      redirect_to new_session_url
    end
  end
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  before_action :require_current_user!, except: [:index, :show]

  def index
    goals = Goal.all
    if current_user
      @personal_goals = goals.where(user_id: current_user.id)
      @public_goals = goals.where(privacy: :Public) - @personal_goals
    else
      @public_goals = goals.where(privacy: :Public)
    end
  end

  def new
    @goal = Goal.new
  end

  def create
    @goal = current_user.goals.new(goals_params)
    if @goal.save
      redirect_to goal_url(@goal)
    else
      flash.now[:notice] = @goal.errors.full_messages
      render :new
    end
  end

  def show
    @goal = Goal.find(params[:id])
  end

  def goals_params
    params.require(:goal).permit(:title, :description, :privacy)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.find_by(username: params[:user][:username])
    if @user && @user.is_password?(params[:user][:password])
      login!(@user)
      redirect_to goals_url
    else
      @user = User.new(username: params[:user][:username])
      flash.now[:notice] = @user.errors.full_messages
      render :new
    end
  end

  def destroy
    logout!
    redirect_to new_session_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login!(@user)
      redirect_to goals_url
    else
      flash.now[:notice] = @user.errors.full_messages
      render :new
    end
  end

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def auth_token
    "<input type='hidden' name='authenticity_token' value='#{form_authenticity_token}'>".html_safe
  end
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/goals/index.html.erb
<h1>Goals</h1>
<% if @personal_goals %>
  <% @personal_goals.each do |goal| %>
    <%= link_to goal.title, goal_url(goal) %> <br>
  <% end %>
<% end %>
<% @public_goals.each do |goal| %>
  <%= link_to goal.title, goal_url(goal) %> <br>
<% end %>
<br><br>
<%= link_to "New Goal", new_goal_url %>

app/views/goals/new.html.erb
<h1>New Goal</h1>

<form action="<%= goals_url %>" method="post">
  <%= auth_token %>
  <label>
    Title
  <input type="text" name="goal[title]" value="<%= @goal.title %>">
  </label>

  <label>
    Description
  <textarea name="goal[description]"
            rows="8"
            cols="40">
            <%= @goal.description %></textarea>
  </label>

  <label>
    Privacy
    <label>
      <input type="radio" name="goal[privacy]" value="Public">
      Public
    </label>

    <label>
      Private
      <input type="radio" name="goal[privacy]" value="Private">
    </label>
  </label>

  <input type="submit" value="Submit">
</form>

app/views/goals/show.html.erb
<h1><%= @goal.title %></h1>
<h4><%= @goal.user.username %>'s goal</h4>
<p>
  <%= @goal.description %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GoalApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if current_user %>
  <%= current_user.username %>
  <%= button_to 'Sign Out', session_url, method: :delete %>
<% end %>

  <% if flash[:notice] %>
    <ul>
      <% flash[:notice].each do |notice| %>
        <li><%= notice %></li>
      <% end %>
    </ul>
  <% end %>  

<%= yield %>

</body>
</html>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<form action="<%= users_url %>" method="post">
<%= auth_token %>
  <label>
  Username
  <input type="text" name="user[username]" value="<%= @user.username %>">
  </label>

  <label>
  Password
  <input type="password" name="user[password]">
  </label>

  <input type="submit" value="Submit">
</form>